<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Constructor de la excepci&oacute;n</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

 </head>
 <body class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="class.exception.html">« Exception</a></li>
      <li style="float: right;"><a href="exception.getmessage.html">Exception::getMessage »</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="class.exception.html">Exception</a></li>
    <li>Constructor de la excepci&oacute;n</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="exception.construct" class="refentry">
 <div class="refnamediv">
  <h1 class="refname">Exception::__construct</h1>
  <p class="verinfo">(PHP 5, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">Exception::__construct</span> &mdash; <span class="dc-title">Constructor de la excepción</span></p>

 </div>

 <div class="refsect1 description" id="refsect1-exception.construct-description">
  <h3 class="title">Descripción</h3>
  <div class="constructorsynopsis dc-description">
   <span class="modifier">public</span> <span class="methodname"><strong>Exception::__construct</strong></span>(<span class="methodparam"><span class="type"><a href="language.types.string.html" class="type string">string</a></span> <code class="parameter">$message</code><span class="initializer"> = &quot;&quot;</span></span>, <span class="methodparam"><span class="type"><a href="language.types.integer.html" class="type int">int</a></span> <code class="parameter">$code</code><span class="initializer"> = 0</span></span>, <span class="methodparam"><span class="type"><span class="type"><a href="language.types.null.html" class="type null">?</a></span><span class="type"><a href="class.throwable.html" class="type Throwable">Throwable</a></span></span> <code class="parameter">$previous</code><span class="initializer"> = <strong><code><a href="reserved.constants.html#constant.null">null</a></code></strong></span></span>)</div>

  <p class="para rdfs-comment">
   Construye el objeto Exception.
  </p>
 </div>


 <div class="refsect1 parameters" id="refsect1-exception.construct-parameters">
  <h3 class="title">Parámetros</h3>
  <p class="para">
   <dl>
    
     <dt><code class="parameter">message</code></dt>
     <dd>
      <p class="para">
       Mensaje de la excepción a lanzar.
      </p>
     </dd>
    
    
     <dt><code class="parameter">code</code></dt>
     <dd>
      <p class="para">
       El código de la excepción.
      </p>
     </dd>
    
    
     <dt><code class="parameter">previous</code></dt>
     <dd>
      <p class="para">
       La excepción previa utilizada por la serie de excepciones.
      </p>
     </dd>
    
   </dl>
  </p>
   <blockquote class="note"><p><strong class="note">Nota</strong>: 
   <span class="simpara">
    Llamar al constructor de la clase Exception de una subclase ignora los
    argumentos por omisión, si las propiedades $code y $message ya están establecidas.
   </span>
  </p></blockquote>
 </div>


 <div class="refsect1 notes" id="refsect1-exception.construct-notes">
  <h3 class="title">Notas</h3>
  <blockquote class="note"><p><strong class="note">Nota</strong>: 
   <p class="para">
    <code class="parameter">message</code> <em>NO</em>
    es seguro binariamente.
   </p>
  </p></blockquote>
 </div>


</div></div></div></body></html>